name: Publish Plugin Portal
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish
        run: ./gradlew :plugin:publishPlugins --validate-only
