name: Publish Plugin Portal
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
      SIGNING_PGP_PASSWORD: ${{ secrets.SIGNING_PGP_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish
        run: ./gradlew :plugin:publishPlugins --validate-only
